### ISSUE TITLE
My Tablet is completly broken

### ISSUE THREAD

**Issue by Luis-Harz** [ryanfortner/FireHD8-2017#2]
I did every command but at the bootrom-minimal it wokred fine but after the restart my tablet is now in a bootloop

**Comment by anthonymesa** [comment]
Ah. Man. This also just happened to me as well. @Luis-Harz, Are you aware of this issue?

**Comment by ryanfortner** [comment]
Good afternoon,

This guide is a compilation of commands & files from the following [XDA thread](https://xdaforums.com/t/master-thread-fire-hd-8-2017-7th-generation.3743024/). When following steps detailed there, I was able to successfully convert my tablet to a full Android, and documented my steps here for later use. If in the event your tablet seems like it's bricked or in an otherwise unusable state, I recommend following the steps listed in "General Tips" for how to return to stock or recover from a soft-brick.

I am far from an expert on Amazon tablets and their software. You will be much better off asking the folks on the XDA forums rather than me if those general tips don't help.

Best of luck!

**Comment by anthonymesa** [comment]
@ryanfortner , I get it lol, I did the same thing with a different tablet :D. @Luis-Harz I know for myself, the issue seems to be that on the XDA thread there was a bit of the guide behind a spoiler tag that I didn't see, and it explicitly says that if you use brick-9820.sh to NOT USE bootrom-step-minimal as it will mess up your device, instead use the normal bootrom-step. I think this was my issue. if you use 9820 and minimal, it wont pull it out of the bricked state (and makes it a bit worse i think). I am working to try and undo this. Currently, with it bricked, i pulled the device apart, applied a wire to TP28 on the back of the mobo to short it to ground, and it is in a hardware-set preloader mode. Now i am just rtying to figure out how to get it back to a point i can work with from this preloader mode, as the bootrom or brick scripts still aren't recognizing it while in this mode.

@ryanfortner It would be good to update your guide with this info, to help keep from others bricking their device with your guide :')

**Comment by Luis-Harz** [comment]
Well the tablet is from my friend I think he will get mad because I made it unuseable

**Comment by Luis-Harz** [comment]
> @ryanfortner, ich verstehe, lol, ich habe dasselbe mit einem anderen Tablet gemacht :D.@Luis-HarzIch weiß von mir selbst, das Problem scheint darin zu liegen, dass sich im XDA-Thread ein Teil der Anleitung hinter einem Spoiler-Tag vermutet, den ich nicht gesehen habe. Darin steht ausdrücklich, dass Sie bei Verwendung von brick-9820.sh NICHT den bootrom-step-minimal VERWENDEN sollen, da dies Ihr Gerät durcheinanderbringen wird. Verwenden Sie stattdessen den normalen Bootrom-Schritt. Ich denke, das war mein Problem. Wenn Sie 9820 und minimal verwenden, wird es nicht aus dem gerickten Zustand herausgezogen (und macht es meiner Meinung nach etwas schlimmer). Ich arbeite daran, dies rückgängig zu machen. Im Moment habe ich das Gerät im gerickten Zustand auseinandergenommen, ein Kabel an TP28 auf der Rückseite des Motherboards angeschlossen, um es kurzzuschließen, und es befindet sich in einem hardwaremäßig eingestellten Preloader-Modus. Jetzt versuche ich nur noch herauszufinden, wie ich es aus diesem Preloader-Modus wieder an einen Punkt bekomme, mit dem ich arbeiten kann, da die Bootrom- oder Brick-Skripte es in diesem Modus immer noch nicht erkennen.
> 
> @ryanfortnerEs wäre gut, wenn Sie Ihre Anleitung mit diesen Informationen aktualisieren würden, um zu verhindern, dass andere ihre Geräte mit Ihrer Anleitung unbrauchbar machen :')

Please tell me if it worked and if so, I really need help

**Comment by anthonymesa** [comment]
@Luis-Harz I will update here if I am able to find a fix that restores my tablet to a point where I can re-run bootrom-step.
